# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9428b9dcde8435f05e44aa30dd96f25ffa3da3a73f46dc1fca4d17d253350f11ccc73b352aa41c2df3164b1d19b0b1984b89a0fc1d9b15c07da1a1ad898ab20c

test:
  secret_key_base: 80f0ba41f9c63e14b89673b088758e81cb2e58e7b3aee8bc482d3b4f02919a39f3b32b4d9e126f75ae3aa56e30c91acf3d29c31d0235baabbb79a0cab611b0dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
